### ISSUE TITLE
can't connect download address

### ISSUE THREAD

**Issue by freemedom** [joelpurra/xmouse-controls#20] opened 2020-09-06 01:57 UTC
can't connect download address.https://files.joelpurra.com/projects/x-mouse-controls/2018-10-06T1730Z/x-mouse_controls_2018-10-06T1730Z_release.zip
Don't know why.

**Comment by joelpurra** [comment] 2020-09-06 05:19
@freemedom: the files are downloaded from a rather underpowered server in the north of Sweden. It was probably just busy at the time, or there was some temporary internet disturbance somewhere. Did you try multiple times? It has been a few hours, perhaps it works now -- can you try again?

The download was just confirmed to work from two different countries. Seems to be fine now, so will close this issue. Please let me know if it fails again. Thank you =)

**Closed as completed** 2020-09-06 05:19 UTC
Labels: bug

**Comment by freemedom** [comment] 2020-09-06 08:15
It seems that IDM is the reason, I turned off IDM, and it downloaded successfully

**Comment by freemedom** [comment] 2020-09-06 08:17
thank you
