### ISSUE TITLE
Can we integrate better with keyboard-driven window switching?

### ISSUE THREAD

**Issue by mentalisttraceur** [joelpurra/xmouse-controls#10] opened 2018-06-14 02:19 UTC
First, a sidenote: Just found this program, and it's great! Thank you for putting it out here and opening the source!

On to the question:

Would you be open to adding a hook to temporarily (until next mouse movement) disable the focus-follows-mouse features upon certain key combinations?

Motivation:

Every Windows focus-follows-mouse solution I've tried has a problem where if you use `Alt+Tab` or `Ctrl+Tab` or otherwise switch window focus using keyboard shortcuts, immediately after, the window under the mouse steals focus again (made worse by `Alt+Tab` and `Ctrl+Tab` repositioning the mouse cursor).

X window managers I've used on Linux don't have this problem: you can mix and match the keyboard and mouse Window focus switching workflows without issue.

I find that when I'm doing a very keyboard-driven things between a couple frequently switched windows I prefer `Alt+Tab` to moving my hand all the way to the mouse, but otherwise prefer using the focus-follows-mouse feature.

Implementation thoughts:

We could have two event handlers:

1. Disable the focus-follow-mouse features. Register the second event listener (if it's not better to just register the second one permanently?)

2. Re-enable the focus-follow-mouse features that were previously enabled.

The first one can be hooked to a user-modifiable list of key stroke combinations, with the default value of the list being `Alt+Tab` and `Ctrl+Tab`.

I don't know if this forces you to re-architect anything or just adds more complexity than you want in this project - I haven't yet looked at your code - but if you're open to going that route I'd be happy to make an attempt at a pull request for it.

**Comment by joelpurra** [comment] 2018-06-17 07:58
@mentalisttraceur: unfortunately, a potential event-driven fix is not within the scope of X-Mouse Controls; it only modifies "hidden" settings in Windows, which takes care of any mouse events.

That said, `Alt+Tab` and similar should work just fine. My guess is that you have set the delay quite low, perhaps even 0 milliseconds -- correct? The recommendation is to set it to 100-250 ms, to allow any menus/multi-document/windows to render properly so it can receive the focus.

The exact minimum delay depends on which programs are running, CPU speed, operating system, and system settings -- adjust to your liking. In case you have installed any other programs modifying the mouse behavior (or perhaps even a custom window manager) you might also need to completely remove them in order to verify that X-Mouse Controls works as intended. See the website for recommendations and common workarounds.
https://joelpurra.com/projects/X-Mouse_Controls/

Does that fix the problem? Also, if anyone else has this specific problem, please chime in.

As this won't be fixed in X-Mouse Controls, I'll close the issue; you can still comment though. Thanks for the suggestions =)

**Closed by joelpurra** 2018-06-17 07:58 UTC
Labels: wontfix

**Comment by mentalisttraceur** [comment] 2018-06-18 19:12
@joelpurra Thanks for considering it anyway. The timeout doesn't mitigate the situations I have in mind, sadly. That's okay though, I understand it's out of scope.

@binki Yeah I noticed that too with Windows automatically moving the cursor sometimes. That sometimes helps but sometimes actually contributes to the problem sometimes (see case two below).

So just to be clear, there's basically two ways where things go wrong, for any usable timeout (Disclaimer: I only work with Windows 7 currently, at work - maybe these are less of a problem on Windows 10):

1. You `Alt+Tab`, but Windows does not automatically move the cursor, and your mouse stays floating over another window: the desired window is focused briefly, but you don't have time to get meaningful typing done into it because any reasonable timeout (even up to one second) will elapse before you're done.

2. You `Alt+Tab`, and Windows automatically moves the cursor for you but there's another window overlapping with the target window's center: you might be switching to a browser or text editor which is maximized to occupy all or half of the screen, and some dialog or small window from another program just happens to have an "always on top" setting and position in the center of the screen - often the larger window has the important stuff in view even if the center of it is covered, or you don't need to see but just need to type).

I don't know what exactly determines whether or not Windows moves the cursor or not as a result of `Alt+Tab`ing, haven't ever sat down to really narrow it down through trial and error.

**Comment by binki** [comment] 2018-06-24 21:17
@mentalisttraceur I see the same behavior on the latest Windows 10 insider builds. I think it’s been that way for a long time. It seems to be less of an issue when running fewer programs, but if you’re maxing out the CPU you can sometimes see the focus linger on the right window before settling on the wrong one or vice versa.

One observation that I have when moving the mouse between windows is that windows that are not running their message pumps can refuse to give up or receive focus, preventing the switch from actually having a 0ms delay. When Windows makes the special [“(Not Responding)” ghost window](https://blogs.technet.microsoft.com/askperf/2010/09/10/de-ghosting-your-windows/), the ghost window always handles receiving/relinquishing focus promptly. However, a program has to be not responding for a long time before it gets a ghost window. I think that this behavior hints at architectural differences between X11 window managers and Windows. Windows waits for a response from a window before defocusing while X11 window managers don’t try to do this and instead simply redirect input. When things are running slowly, I think this sometimes changes the results of alt+tab.

I should be more active about submitting feedbacks through the Feedback thing because only MS can fix these issues properly, though I also have not taken the time to find the precise conditions for each issue…

**Comment by gwebbgit** [comment] 2024-07-07 00:26
It's now 2024, and I've been suffering with this annoyance for many years now:  Alt-Tab switches to the correct window, but somehow the mouse cursor pulls it to the wrong window.  So I just try Alt-Tab again and again until it finally switches correctly.  Or give up and just move the mouse.

It seems *sometimes* the mouse moves with Alt-Tab to the newly chosen window (to the center of it), and sometimes it doesn't.  What causes this inconsistent behavior?

Can we workaround this issue with a AutoHotKey script perhaps?  

(Should this be a new issue?  I realize it's probably not an XMouse-Controls issue.)

Thank you!

**Comment by mentalisttraceur** [comment] 2024-07-08 14:08
Nowadays, I'd be tempted to write an autohotkey script, should be just ~3-6 lines long: 

On start of mouse movement, launch XMouse-Controls if it isn't already running.

On Alt-Tab, Ctrl-Tab, any others you want, kill XMouse-Controls.

**Comment by binki** [comment] 2024-07-08 14:13
> Nowadays, I'd be tempted to write an autohotkey script, should be just ~3-6 lines long:
> 
> On start of mouse movement, launch XMouse-Controls if it isn't already running.
> 
> On Alt-Tab, Ctrl-Tab, any others you want, kill XMouse-Controls.

This indicates a misunderstanding of how XMouse-Controls works. The behavior of Windows does not change if the program is running or not. The program makes a permanent configuration change. You only run it when setting things up initially.

If you wanted to switch settings using an AutoHotKey script, you might read the source and have your script simply alter the registry or make whatever system call there is (if necessary) to get Windows to notice the change. I haven’t spent the time looking at the source, but it should be all there and well-documented. You can see some discussion on approaches at https://joelpurra.com/projects/X-Mouse_Controls/ under “Search engine fodder”.

**Comment by joelpurra** [comment] 2024-07-08 16:46
@gwebbgit: correct -- the inconsistent mouse cursor movement/behavior is not (directly) related to the functionality of X-Mouse Controls. It is a side-effect of how Windows (for this issue, in particular <kbd>alt-tab</kbd>) and each individual program handles focus.

If you can identify a program which steals/keeps/"re-steals" focus, it'd be best to report the issue to the developers of each individual program. (Including Windows and other Microsoft software.)

@mentalisttraceur: @binki is correct. X-Mouse Controls does not use mouse or focus event listeners, nor does X-Mouse Controls have to be "running" since all settings are persisted by Windows itself.

X-Mouse Controls is not intended for automation, but you can implement all settings/features for automation in other ways. Perhaps PowerShell?

- https://github.com/joelpurra/xmouse-controls/issues/22#issuecomment-833407576

**Comment by joelpurra** [comment] 2024-07-08 16:58
By the way, I seem to recall there being an option somewhere in Windows to "warp" the mouse cursor to the "default button" in a (newly opened?) window. It's another example one of the things which can completely change how focus works in the window manager. Perhaps it can be abused in some clever way?

Might even have been a hidden setting from back in the Windows 3.11 days though (yes, the early 1990s), when I started using X-Mouse in Windows ;)

Does it still exist in Windows 11, perhaps as a hidden accessibility option? (Am still on Windows 10, but only rarely boot to it.)

Maybe it was part of Microsoft PowerToys, pre-Windows Vista. Might be part of the modern reimplementation?

- https://github.com/microsoft/PowerToys

**Comment by binki** [comment] 2024-07-08 17:04
@joelpurra 
> By the way, I seem to recall there being an option somewhere in Windows to "warp" the mouse cursor to the "default button" in a (newly opened?) window. It's another example one of the things which can completely change how focus works in the window manager. Perhaps it can be abused in some clever way?

This is still in Windows. Not sure when it appeared, but you can get to it through Settings / Bluetooth and Devices / Mouse / Additional settings / Pointer Options even in the latest Windows 11 builds:

![image](https://github.com/joelpurra/xmouse-controls/assets/82626/0da3730f-2c1f-4979-b4ea-8b0eae6f41a2)

I think I tried this many years ago and I did not like how an unexpected dialog changed where my mouse was. I expect this feature to cause misclicks.

**Comment by joelpurra** [comment] 2024-07-08 17:11
@binki: ah, yes -- thanks for finding it! Looks like it's a leftover part of the older Control Panel style settings.

> I think I tried this many years ago and I did not like how an unexpected dialog changed where my mouse was. I expect this feature to cause misclicks.

Yeah, I would assume it takes some getting used to. The question is whether it makes <kbd>alt-tab</kbd> more consistent? Perhaps it requires a default button to "snap to" though, which is not available in all programs/windows. (Also, the feature wording is "dialog box" not "window".)

**Comment by binki** [comment] 2024-07-08 17:12
However, to note, I do not think that the default button feature would really apply. I don’t know if it even works with modernish dialogs (would need to try it). It is not for all new windows. It was only for ones with a default “OK” or “Yes” button.

Speaking to the alt-tab behavior. I do find that annoying too. Sometimes I use win+tab and click on the window I want to get past it. Sometimes I just spam alt-tab until the right window pops up (normally the desired window becomes the second in the alt-tab list after you first try to switch to it). Sometimes I click on a window in the taskbar because of this behavior. Sometimes (especially when using Remote Desktop—I wish I knew how to trigger/force it) Windows misses the trigger to launch the modern alt-tab experience with window thumbnails and instead displays the old-style one with icons. The old version seems not to have the issue with raising the new window. The modern one seems to itself receive focus as if it is a window which causes this problem. Maybe I need to find time and try to report this as Windows feedback. I almost wish I could just disable the new experience sometimes though.

This isn’t to mention that some applications just are bad at focus. For example, LINE is almost impossible to raise. And Kakaotalk likes to close windows which lose focus which makes some windows completely unusable (if you click in one window to launch another window, the moment you start moving your mouse out of the bounds of the original window, the new window disappears). These issues need to be fixed by app developers but I wouldn’t know how to convince these developers to prioritize this, hehe.

**Comment by joelpurra** [comment] 2024-07-08 17:42
@binki

> Sometimes (especially when using Remote Desktop—I wish I knew how to trigger/force it) Windows misses the trigger to launch the modern alt-tab experience with window thumbnails and instead displays the old-style one with icons. The old version seems not to have the issue with raising the new window. The modern one seems to itself receive focus as if it is a window which causes this problem. Maybe I need to find time and try to report this as Windows feedback. I almost wish I could just disable the new experience sometimes though.

There seems to be an `Explorer.exe`-related registry hack `AltTabSettings`, which can enable the "classic" <kbd>alt-tab</kbd> experience. A random website says it still works for Windows 11.

- https://superuser.com/questions/114001/getting-back-the-old-alt-tab-windows-switching-behavior-in-windows-7
- https://superuser.com/a/114058

Interestingly, the same Q&A lists an old answer on how to trigger it by pressing both left and right <kbd>alt</kbd> buttons in a sequence. Perhaps that's related to how you triggered it over Remote Desktop?

- https://superuser.com/a/114047

**Comment by mentalisttraceur** [comment] 2024-07-10 20:05
> This indicates a misunderstanding of how XMouse-Controls works. The behavior of Windows does not change if the program is running or not. The program makes a permanent configuration change. You only run it when setting things up initially.

Yeah, I forgot. It has been many years since I used XMouse-Controls (I basically stopped back when I created this issue 6 years ago). The concept of my hack is the same, just replace starting/stopping with setting/unsetting (I suppose at that point XMouse-Controls might be redundant).

**Comment by gwebbgit** [comment] 2024-07-16 21:21
I've had so much trouble with Alt+Tab switching either not switching to the correct window or taking too long to show the pop-up, as others have described above.  Lately, I disabled X-Mouse entirely and discovered that those problems have disappeared -- Alt-Tab popup shows consistently right away and the chosen window focuses consistently correctly.  Now, of course, I miss the X-Mouse behavior, but at least now I can isolate the problem and either a) re-create my own X-Mouse behavior using AutoHotKey or a 3rd-party app or b) re-create the Alt-Tab behavior using AHK or some 3rd-party app.

Or maybe I or someone will figure out why X-Mouse and `Alt+Tab` work so poorly together.

(It's not X-Mouse Controls' problem either!  But maybe users can help...thanks!)

**Comment by gwebbgit** [comment] 2024-07-27 01:45
...actually I'm wrong--disabling X-Mouse entirely does not completely resolve `Alt-Tab` focusing issues.  I found that even with X-Mouse disabled, *sometimes* `Alt-Tab` focusing fails to raise the targeted window.  I don't know why, but I'd bet it's probably app-window specific.  Some app-windows are just stubborn to consistently raise themselves by any means other than explicitly clicking on their title bar.  Clicking seems like the only 100% positive way to raise a window.  There must be a hack for this problem...?
