### ISSUE TITLE
website for downloads unreachable

### ISSUE THREAD

**Issue by ahnkle** [joelpurra/xmouse-controls#4] opened 2017-03-03 10:47 UTC
When I try to go to https://joelpurra.com/, firefox is unable to load the site.

**Comment by joelpurra** [comment] 2017-03-03 13:04
@ahnkle: you are quite right. It's not a server fault though, but a network connection problem. There seems to be [a "major fault" in the area where my server host is located](https://quitter.se/notice/9888236), and the connection has been unstable for several hours yesterday and today. Unfortunately not much to do about it but wait for the network connection to be fixed, which "should" not be more than a few hours.

By the way, it seems as if [the website is reachable at this very moment](https://joelpurra.com/projects/X-Mouse_Controls/). Can't guarantee that it stays up for much longer, but do try again!

Closing as the problem is out of my control, yet assumed to be fixed "shortly". Let's hope the network techies work fast. Thanks for the report =)

**Closed by joelpurra** 2017-03-03 13:04 UTC
