### ISSUE TITLE
Maybe at a keyboard shortcut to toggle between on/off

### ISSUE THREAD

**Issue by OgierM** [joelpurra/xmouse-controls#7] opened 2017-07-20 15:11 UTC
On Windows 10, some notifications lose focus when you hover over them.

**Comment by binki** [comment] 2017-07-22 04:40
Could you describe more precisely what sort of notifications you’re having an issue with? I haven’t noticed the toasts (the notifications which show up in the Action Center if you don’t click on them right away) giving me any issue at all when using 0ms focus follows mouse. I.e., they stay around even if you mouse over them and then mouse out from them. Maybe you’re referring to some other sort of notification than I’m thinking of.

One technique I use with such notifications when they stay around too long is to just press Windows+a to show the Action Center. That causes the Action Center to soak up the notification. You can immediately press Windows+a again to hide the Action Center and then continue with what you were doing (sometimes for me the notifications cover text I’m trying to read or stuff I’m trying to click on). This also lets you more safely deal with the notification in the Action Center instead of trying to interact with the notification.

**Comment by OgierM** [comment] 2017-07-22 09:23
The tray, some Apps that have menus that open from the tray (like Google Drive) and the action center itself go away immediately if I hover over them. I can avoid this by clicking and then moving the mouse fast upwards, so that it is on the right position before the tray/action center is actually there (action center is easier, because the animation is a tad longer). I only use the focus follows mouse option and 0ms in xmouse controls.

**Comment by binki** [comment] 2017-07-22 19:06
Ah. I normally don’t open the action center using the button, so I don’t notice that. On my computer, when I click the Action Center button and move my mouse to the Action Center, it doesn’t close. But if I move my mouse over the date/time display on the taskbar before reaching the Action Center, the Action Center closes. This reminds me of issues with MDI windows and such stuff mentioned in [the docs for xmouse-controls](https://joelpurra.com/projects/X-Mouse_Controls/) under the “Notes” heading:

> * Some applications, especially those with a [Multiple Document Interface](https://en.wikipedia.org/wiki/Multiple_document_interface), may raise their own window even though the feature is disabled. See work-around below.
> * Some menus do not like the x-mouse behavior and close before you are able to reach or click any menu alternative. See work-around below.
>*  One workaround to avoid window raising and menu problems is to click and hold your left mouse button on an empty (unresponsive) area, drag the cursor to where you want to focus and let go. 

If I follow the instructions in the last bullet point, I can move my mouse from the Action Center button to the Action Center even if I accidentally move the mouse over the date/time display in my taskbar instead of directly to the Action Center. Please try this and let us know if it works for you.

Regarding the systray: I think I have seen it where right-clicking or clicking on a systray icon results in the menu popping under the Task Bar. When that happens, it can be hard to interact with. But right now for me the menus appear above the Task Bar so I cannot repro your Google Drive example (but I don’t have Google Drive installed so I’m testing with opening the menu for Sugarsync and OneDrive). In any case, the menus always pop up so that you can move your mouse over the menu without having to mouse over another window. The issue is when a menu pops up (and I can’t find any today) where the menu is not right next to the mouse. When moving the mouse to the menu, your mouse might be over a window in the background which, with focus follows mouse, might focus the window behind it, causing the menu to disappear. I recommend you try the left-click-drag trick or try the same trick but holding the right mouse button instead of the left mouse button (if you left-drag a systray icon it moves it but right-click drag should let you get to the menu without disturbing anything).

Note: I use the settings focus follows mouse, 0ms, no raise.

Regarding your keyboard shortcut suggestion, as I am not the developer, I cannot really say, but one nice feature about XMouse Controls as it is is that it is just a GUI around a simple registry change. Once you use the XMouse Controls GUI to configure the behavior, you can completely throw away the executable. If a keyboard shortcut to toggle the mode were required, you’d have to run the program for as long as you want the shortcut to work. I don’t know if this feature would be added, so hopefully in the meantime the suggested workarounds/tricks might be useful?

**Comment by joelpurra** [comment] 2017-08-07 20:07
Hey guys @OgierM @binki,

Sorry for the delayed reply. Not using Windows 10 on my personal computer (wasn't paying attention at all and missed the free upgrade period; now my current hardware doesn't support Windows 7 and I'm a bit stuck) and can't test this specific case. Sorry about that. Did set up a new virtual machine a few weekends ago, but haven't gotten it back to development status yet. Sadface.

Afraid that adding keyboard shortcuts will be _a lot_ of hassle for such a small application as X-Mouse Controls. It's not "just" about adding a shortcut; it's keeping the application either "completely hidden" or "kind of hidden" in the systray while listening for keyboard input. Minimization would probably not cut it.

That's not all though: keyboard shortcuts are prime property, and therefore they need a _shortcut manager_ so users can pick one that is not already occupied on their system. There are no guaranteed free keys, especially for power-users such as X-Mouse Controls' users.

Can give my "generic" long-time X-Mouse user and developer input though (20+ years now). Please use focus follow mouse with a 100-200 millisecond delay, and if that doesn't work in _each and every case_, use the [MDI](https://en.wikipedia.org/wiki/Multiple_document_interface) workaround both mentioned by @binki and the docs: click an "empty"/"dead"/"unresponsive" area and drag the mouse pointer to your desired menu. This setup has worked for me for years, even back in the Windows 95 plus TweakUI days. (Perhaps even Windows 3, can't remember any more.)

Feedback? @OgierM did you manage to work it out given the tips from @binki?

Appreciate that you took the time to give proper feedback. Thanks! =)

Closing this issue for now, as I don't see a great use-case for shortcut keys. Please enlighten me with if they are _really_ needed.

**Closed by joelpurra** 2017-08-07 20:07 UTC
